### ISSUE TITLE
Image for issue (I put it on debatemap/feedback but imma let github host the image)

### ISSUE THREAD

**Issue by acenturyandabit** [debate-map/app#17]
![image](https://user-images.githubusercontent.com/33882353/127763908-87f70af5-ce0b-45d0-9c70-3fa2afdbd530.png)

**Comment by Venryx** [comment]
Yes, sorry about that. It is a bug due to the flimsy code used for initializing a user's data on sign-up. The new version already has this particular bug fixed, but it's not online yet. (should be in a few days)

By the way, I do not have email notifications for the entries added on the Debate Map feedback page yet. That's another thing I _really_ need to add soon, as I've missed a number of bug-reports/feature-requests because of it. (adding that to my priority list)
