### ISSUE TITLE
Problem with signing in with chrome

### ISSUE THREAD

**Issue by v-ko** [debate-map/app#5]
When trying to sign in , clicking on the button "Sign in" just shows a caption "Signing in only takes 30 seconds" and nothing happens. 
Browser: Version 76.0.3809.132 (Official Build) (64-bit), OS: Manjaro linux

**Comment by Venryx** [comment]
This is what it looks like to me: https://i.imgur.com/jYBNpkp.png

I'm assuming for you all the colored buttons are missing, and you only see that header text.

I'm not sure what could have caused this...

**Comment by drared** [comment]
I tried signing in with firefox and chrome on both debate.live and canonicaldebate.com. 
I didn't find any issues. 
I normally use firefox. When I tested in chrome it originally showed the colored bars with the various sign-in options. After signing in and out, it only shows the '**sign-in with google**' option. Not sure if this is the desired operation. It suits me...

**Comment by Venryx** [comment]
The canonicaldebate.com website (the new version) only shows the "sign-in with google" option for now, since it takes some setup for the others. (my screenshot is from the old debate-map site -- though taken this morning)

I'm guessing it might have to do with @petko10's operating system (Manjaro linux).

I've never heard of it before. Perhaps it has some unusual security or graphics/driver details which cause the popup to get cut off. I did notice some issues with content being cut off before, and fixed it with a css modification -- but perhaps that css modification doesn't work correctly on his platform/device.

**Comment by drared** [comment]
If it was something that simple, petko10 could probably confirm by looking at the site via the developers inspect tool. Even if it was hidden, it would still appear in the html...

**Comment by Venryx** [comment]
Good point. Can you check that for us @petko10 ? Look for descendants of that popup container that have the text of the buttons in my screenshot.

**Comment by v-ko** [comment]
Sorry, guys, it was the Adblock Plus extension that was hiding the login menu entries (for some buggy reason..).
 Thank you for the great work on DebateMap. For years now I've been thinking about a system for this kind of online debates, and I'm glad I'm not alone.

**Comment by Venryx** [comment]
Thank you for your comments! Hope you find it encouraging to hear that I plan to work on this project for the rest of my life, and that I consider it one of my main life goals. (probably the main one, because of how vital I believe it will be for reducing tension between opposing groups and helping people more efficiently evaluate claims -- though I do have some other long-term projects as well)

If you haven't seen the note yet, I recently added a message to this project's readme linking to the new version of the project. The new version is called "Canonical Debate" instead of "Debate Map". I personally don't like the name as much, but it's the name the group I'm collaborating with decided on for now. While there is some loss of control when joining a collaboration, I figured it was probably worth it in the long-run, for a few different reasons. (It's all open-source anyway, so if there end up being major conflicts in the future, it's not like any of the work gets wasted either way, thankfully.)

**Comment by v-ko** [comment]
I'm glad to see such dedication. I also believe such a system will be indispensable in the future of the internet and collaboration in general. Your project is the only one I've found to cover the technical requirements for proper debate (minimalist argument formulation, addressing relevance as well as accuracy with arguments, adding context, definitions, etc.).
 I saw there is a slack channel - is that the main place for discussion on the development? I want to join in and learn more about your plans and potentially share some of my ideas as well.

**Comment by Venryx** [comment]
Yes, that's the main place for discussion on the development currently. I'd like to get an "open forum"/channel set up at some point (so people can see the discussions without signing in), but some others in the group are skeptical of the alternatives listed so far. (I think mostly they're just used to Slack :P)

You're very welcome to join us! We're not the most... focused/streamlined group (I guess that's what happens when no one is getting paid XD), but we'll consider your suggestions and most likely have thoughts to add to them.
